# Лабораторная работа 1. Язык Python, основные библиотеки для анализа данных.

ФИО: Каюмов Эмиль Марселевич

Группа: 317

In [1]:
import numpy as np
import pandas as pd

## Часть 1: Python

#### 1. Напишите код, который сформирует список всех натуральных чисел, не превосходящих 100, которые делятся на 7 и не делятся на 5. Нельзя использовать циклы — выполните это задание с помощью list comprehension.

In [2]:
[x for x in range(101) if x % 7 == 0 and x % 5 != 0]

[7, 14, 21, 28, 42, 49, 56, 63, 77, 84, 91, 98]

#### 2. Напишите функцию `sort_tokens(s)`, которая принимает на вход строку, разделяет ее на токены по запятым, сортирует токены с помощью функции `sorted()` и снова соединяет их в одну строку через запятые. Например, для строки `u"ночь,фонарь,улица"` функция должна выдать `u"ночь,улица,фонарь"`. Придумайте несколько входных строк и протестируйте функцию на них.

Обратите внимание, что склеить строки можно с помощью конструкции `'x'.join(...)`. Например:

In [3]:
'! '.join(['i', 'am', 'very', 'excited', ':-)'])

'i! am! very! excited! :-)'

In [4]:
def sort_tokens(s):
    return ','.join(sorted(s.split(',')))

In [5]:
sort_tokens("ночь,фонарь,улица")

'ночь,улица,фонарь'

#### 3. Напишите функцию `remove_duplicates(a)`, которая принимает на вход список и возвращает его же, но без дубликатов и в отсортированном виде. Например, для списка `[u"ночь", u"улица", u"фонарь", u"аптека", u"аптека", u"улица", u"фонарь"]` результат должен быть `[u"аптека", u"ночь", u"улица", u"фонарь", ]`.

Подсказка: обратите внимание на структуру `set`!

In [6]:
def remove_duplicates(a):
    return sorted(list(set(a)))

In [7]:
remove_duplicates(["ночь", "улица", "фонарь", "аптека", "аптека", "улица", "фонарь"])

['аптека', 'ночь', 'улица', 'фонарь']

#### 4. Напишите функцию `word_counts(texts)`, которая принимает на вход список строк, и печатает пары (слово, число вхождений). Считайте, что слова в текстах могут быть разделены только пробелами. Например, для входа `[u'ночь улица фонарь аптека', u'аптека улица фонарь']` должно быть напечатано
>аптека 2

>улица 2

>фонарь 2

>ночь 1

Подсказки:

Чтобы разбить каждый из текстов на слова, воспользуйтесь функцией `map`, которая применяет заданную функцию к каждому элементу списка. Например, если бы нужно было каждый из текстов привести к нижнему регистру, то команда выглядела бы так:

In [8]:
list(map(lambda x: x.lower(), ["abCDefg", "HIjkL"]))

['abcdefg', 'hijkl']

После первого шага вы получите список, состоящий из списков слов. Чтобы объединить их в один список слов, воспользуйтесь функцией `reduce`. Например, просуммировать числа из списка с ее помощью можно так:



In [9]:
from functools import reduce
reduce(lambda x, y: x + y, [1, 2, 3, 4, 5])

15

Для подсчета количества вхождений слов воспользуйтесь структурой `defaultdict` из модуля `collections`. В отличие от обычного `dict`, она не генерирует ошибку при обращении к несуществущему ключу, а создает новую запись, инициализируемую нулевым значением. Например:

In [10]:
from collections import defaultdict
d = defaultdict(int)
print(d)
d['abc'] += 1
print(d)
d['xxx']
print(d)

defaultdict(<class 'int'>, {})
defaultdict(<class 'int'>, {'abc': 1})
defaultdict(<class 'int'>, {'xxx': 0, 'abc': 1})


In [11]:
def word_counts(texts):
    s = list(map(lambda x: x.split(' '), texts))
    s = reduce(lambda x, y: x + y, s, [])
    words = defaultdict(int)
    for i in s:
        words[i] += 1
    for i in sorted(words.keys()):
        print(i, words[i])

In [12]:
word_counts(['ночь улица фонарь аптека', 'аптека улица фонарь'])

аптека 2
ночь 1
улица 2
фонарь 2


#### 5. (бонусное задание) Скачайте английский перевод "Преступления и наказания". Найдите 20 самых популярных слов и 20 слов, которые встречаются только один раз.

Приведите текст к нижнему регистру. Удалите из него все специальные символы и цифры. Разделите текст на слова, считая разделителями все, кроме букв. Обратите внимание на функцию `split` из модуля `re`.

Не забудьте удалить пустые слова:
```
words = filter(lambda x: len(x) > 0, words)
```

In [13]:
from urllib.request import urlopen
from re import split
url = "http://www.gutenberg.org/files/2554/2554.txt"
response = urlopen(url)
raw_text = response.read().decode('utf8')

In [14]:
words = list(map(lambda x: x.lower(), split('\W+', raw_text)))
words = list(filter(lambda x: len(x) > 0, words))
words_dict = defaultdict(int)
for i in words:
    words_dict[i] += 1

In [15]:
words_list = np.array(list(words_dict.keys()))
words_count = np.array(list(words_dict.values()))
words_list = words_list[words_count.argsort()[::-1]]

In [16]:
print('20 самых встречаемых слов:')
for i in range(20):
    print(i+1, '. ', words_list[i], sep='')

20 самых встречаемых слов:
1. the
2. and
3. to
4. he
5. a
6. i
7. you
8. of
9. it
10. that
11. in
12. was
13. his
14. at
15. her
16. but
17. not
18. s
19. with
20. she


In [17]:
print('20 слов, встречающихся один раз:')
for i in range(20):
    print(i+1, '. ', words_list[-(i+1)], sep='')

20 слов, встречающихся один раз:
1. graveclothes
2. stroke
3. resembled
4. embankment
5. criticise
6. ceremonious
7. tyrant
8. wreaths
9. criers
10. attach
11. punctiliousness
12. redeemer
13. devour
14. maiden
15. surmise
16. signalling
17. presentiments
18. wreathed
19. proclaim
20. commented


## Часть 2: NumPy и SciPy

#### 1. Повторите 1000 раз следующий эксперимент: сгенерируйте две матрицы размера $10 \times 10$ из стандартного нормального распределения, перемножьте их (как матрицы) и найдите максимальный элемент. Какое среднее значение по экспериментам у максимальных элементов? 95-процентная квантиль?

Для вычисления квантили воспользуйтесь функцией `np.percentile`

In [18]:
max_element = np.zeros(0)
for i in range(1000):
    matrix1 = np.random.randn(10, 10)
    matrix2 = np.random.randn(10, 10)
    matrix3 = np.dot(matrix1, matrix2)
    max_element = np.append(max_element, matrix3.max())
print('max average =', max_element.mean())
print('95% quantile =', np.percentile(max_element, 95))

max average = 8.41445271949
95% quantile = 12.1333313206


#### 2. Сгенерируйте 1000 чисел из распределения Пуассона с параметром $\lambda = 5$. Сформируйте массив, в котором в i-м элементе будет записано количество сгенерированных чисел, равных i.

Обратите внимание на функцию `np.bincount`

In [19]:
numbers = np.array(np.random.poisson(lam=5, size=1000))
count = np.bincount(numbers)
print(count)

[ 10  39  90 135 167 154 154 104  69  37  22  11   2   2   4]


#### 3. Реализуйте функцию, которая принимает на вход numpy-массив целых чисел `a`, и генерирует массив, в котором число `i` встречается `a[i]` раз. Протестируйте на результате из прошлого задания.

Обратите внимание на функцию `np.repeat`

In [20]:
def repeat_number(x):
    return np.repeat(range(1, len(x)+1), x)

In [21]:
print(repeat_number(count))

[ 1  1  1  1  1  1  1  1  1  1  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2
  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  2  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3  3
  3  3  3  3  3  3  3  3  3  3  3  3  3  3  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4
  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  4  5
  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5
  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5  5
  5  5  5  5

#### 4. Напишите функцию `scale(X)`, которая принимает на вход матрицу и масштабирует каждый ее столбец (вычитает среднее и делит на стандартное отклонение). Убедитесь, что в функции не будет происходить деления на ноль. Протестируйте на каких-нибудь данных.

In [22]:
def scale(X):
    for i in range(X.shape[1]):
        #print(X[:,i].mean())
        X[:,i] -= X[:,i].mean()
        #print(X[:,i])
        std = X[:,i].std()
        if std > 0:
            X[:,i] /= std
    return(X)

In [23]:
X = np.random.rand(6, 6)
print(scale(X))

[[-1.0791069   1.19291051  1.13830678 -0.47732217 -1.50454269  0.6943768 ]
 [ 0.10097177 -1.01791658 -1.02877584  1.56475523  0.5987716  -0.40113429]
 [-1.20564924  0.39688947  1.06834436 -1.15169648 -1.14410305 -1.08912589]
 [-0.19463253  0.70024706  0.59606864 -0.09349432  0.94671343 -1.13980303]
 [ 1.69191494  0.38466617 -0.35041725  1.07288966  1.08266603  1.67429387]
 [ 0.68650195 -1.65679663 -1.42352669 -0.91513192  0.02049468  0.26139253]]


#### 5. Сгенерируйте матрицу с элементами из нормального распределения $\mathcal{N}(10, 1)$. Найдите ее:
- определитель
- след
- наименьший и наибольший элементы
- спектральную норму
- норму Фробениуса
- собственные числа
- обратную матрицу

In [24]:
X = np.random.normal(loc=10.0, scale=1.0, size=(3, 3))
print('det(X) =', np.linalg.det(X))
print('trace(X) =', X.trace())
print('max element =', X.max())
print('min element =', X.min())
print('spectral norm =', np.linalg.norm(X, ord=2))
print('fro norm =', np.linalg.norm(X, ord='fro'))
print('eigvals = ', np.linalg.eigvals(X))
print('inverse matrix =', np.linalg.inv(X))

det(X) = 28.0597155029
trace(X) = 33.1784503462
max element = 12.2692483535
min element = 9.47614086329
spectral norm = 32.1598088668
fro norm = 32.1985815109
eigvals =  [ 32.12158306+0.j           0.52843364+0.77091178j   0.52843364-0.77091178j]
inverse matrix = [[ 0.19714801 -0.87125892  0.69952124]
 [ 0.33025181  0.75841532 -0.99653612]
 [-0.45755373  0.15288674  0.28542564]]


## Часть 3: Pandas

#### Ответьте на вопросы о данных по авиарейсам в США за январь-апрель 2008 года.

Данные: http://stat-computing.org/dataexpo/2009/2008.csv.bz2
(обратите внимание, что распаковывать этот файл не обязательно — функция `pandas.read_csv` умеет читать из архивов автоматически)

Описание: http://stat-computing.org/dataexpo/2009/the-data.html

1. Какая из причин отмены рейса (`CancellationCode`) была самой частой? (расшифровки кодов можно найти в описании данных)
2. Найдите среднее, минимальное и максимальное расстояние, пройденное самолетом.
3. Не выглядит ли подозрительным минимальное пройденное расстояние? В какие дни и на каких рейсах оно было? Какое расстояние было пройдено этими же рейсами в другие дни?
4. Из какого аэропорта было произведено больше всего вылетов? В каком городе он находится?
5. Найдите для каждого аэропорта среднее время полета (`AirTime`) по всем вылетевшим из него рейсам. Какой аэропорт имеет наибольшее значение этого показателя?
6. Найдите аэропорт, у которого наибольшая доля задержанных (`DepDelay > 0`) рейсов. Исключите при этом из рассмотрения аэропорты, из которых было отправлено меньше 1000 рейсов (используйте функцию `filter` после `groupby`).

In [25]:
data = pd.read_csv('2008.csv.bz2')

#### 1. Самая частая причина отмены рейсов

In [26]:
print('самая частая причина отмены: ', data.groupby('CancellationCode').size().argmax())
print('B - погода')

самая частая причина отмены:  B
B - погода


#### 2. Среднее, минимальное и максимальное расстояния, пройденные самолётами, в милях

In [27]:
print('среднее расстояние:', data['Distance'].mean())
print('минимальное расстояние:', data['Distance'].min())
print('максимальное расстояние:', data['Distance'].max())

среднее расстояние: 726.3870294253928
минимальное расстояние: 11
максимальное расстояние: 4962


#### 3. Подозрительно короткий маршрут

In [28]:
data[data['Distance'] == data['Distance'].min()][['Year', 'Month', 'DayofMonth', 'Distance', 'FlightNum']]

Year  Month  DayofMonth  Distance  FlightNum
2547298  2008      5          15        11       4988
4392215  2008      8          10        11       5572

In [29]:
print('средняя длина этих рейсов:')
print('4988:', data[data['FlightNum'] == 4988]['Distance'].mean())
print('5572:', data[data['FlightNum'] == 5572]['Distance'].mean())

средняя длина этих рейсов:
4988: 770.2088888888889
5572: 384.75181598062954


#### 4. Аэропорт с наибольшим числов вылетов

In [30]:
print('больше всего вылетов из:', data.groupby('Origin').size().argmax())
print('количество вылетов:', data.groupby('Origin').size().max())
print('ATL:', 'William B Hartsfield-Atlanta Intl', 'Atlanta', 'USA')

больше всего вылетов из: ATL
количество вылетов: 414513
ATL: William B Hartsfield-Atlanta Intl Atlanta USA


#### 5. Среднее время полёта по аэропортам отправления

In [31]:
print(data.groupby('Origin').mean()['AirTime'])

Origin
ABE     89.057518
ABI     36.789977
ABQ     91.657166
ABY     35.379759
ACK     50.692124
ACT     29.875977
ACV     58.850658
ACY    108.848214
ADK    151.423913
ADQ     41.987934
AEX     68.543556
AGS     36.933814
AKN     37.321429
ALB    101.860527
ALO     36.373134
AMA     56.196001
ANC    156.163749
ASE     48.307996
ATL     93.320419
ATW     50.696326
AUS    101.266600
AVL     69.899021
AVP     94.665204
AZO     34.846602
BDL    118.701612
BET     57.597815
BFL     64.024511
BGM     66.582260
BGR     90.211095
BHM     82.290713
          ...    
SPS     29.490040
SRQ    103.083807
STL     99.294409
STT    168.681929
STX    168.101176
SUN     48.221851
SUX     44.918919
SWF    132.768826
SYR     84.524087
TEX     93.124183
TLH     59.293080
TOL     48.295047
TPA    117.917963
TRI     47.871046
TUL     80.876802
TUP     42.900000
TUS     92.801864
TVC     49.328770
TWF     41.316563
TXK     43.796312
TYR     30.372715
TYS     81.030894
VLD     45.158351
VPS     75.231116
WRG

In [32]:
print('наибольший показатель:', data.groupby('Origin').mean()['AirTime'].argmax())
print('Luis Munoz Marin International', 'San Juan', 'USA')

наибольший показатель: SJU
Luis Munoz Marin International San Juan USA


#### 6. Наибольшая доля задержанных рейсов

In [33]:
airports = data.groupby('Origin').filter(lambda x: x['Origin'].count() >= 1000).groupby('Origin')

In [34]:
name_airport = np.zeros(0, dtype=str)
delay_airport = np.zeros(0, dtype=float)

for airport in airports:
    name_airport = np.append(name_airport, airport[0])
    delay_airport = np.append(delay_airport, np.sum(airport[1]['DepDelay'] > 0) / len(airport[1]))


In [35]:
print('аэропорт с наибольшей долей задержанных рейсов:', name_airport[delay_airport.argmax()])
print('доля задержанных рейсов', delay_airport.max())


аэропорт с наибольшей долей задержанных рейсов: DAL
доля задержанных рейсов 0.578641892894
